### ISSUE TITLE
Highlight for nested properties?

### ISSUE THREAD

**Issue by Roy-Orbison** [hail2u/vim-css3-syntax#54]
SCSS supports the following notation:
```scss
.foo {
   font: {
      size: 160%;
      weight: bold;
   }
}
```
The suffixes do not get highlighted correctly unless they match existing properties, like `top:`. Is this even possible?
