### ISSUE TITLE
space-between not highlight

### ISSUE THREAD

**Issue by othree** [hail2u/vim-css3-syntax#59]
```css
foo {
   display: flex;
   justify-content: space-between;
}
```

The `space-between` part is not highlight correctly.
Its because the `space` is a [keyword][1] and have higher priority.
I believe other value starts with `space` are all effected.

[1]:https://github.com/hail2u/vim-css3-syntax/blob/99583cc304d8c219cd1467544ee2c7435b97756e/after/syntax/css/css-backgrounds-3.vim#L5
