### ISSUE TITLE
Color preview is also applied to CSS property names

### ISSUE THREAD

**Issue by Tomalak** [hail2u/vim-css3-syntax#72]
```css
div.test {
    white-space: nowrap;
}
```

currently ([v2.0.0](https://github.com/hail2u/vim-css3-syntax/releases/tag/v2.0.0)) shows up like this:

![image](https://user-images.githubusercontent.com/28300/225652976-8c7ef223-076e-4be5-9c7f-c8263b739841.png)

Color names should only be taken into account for property values.
